### ISSUE TITLE
akshare\stock_zt_pool_em.py出错

### ISSUE THREAD

**Issue by quantcn** [wukan1986/ddump#2]
运行akshare\stock_zt_pool_em.py，报如下错误，怎么解决呢?

2024-07-29 22:13:12.614 | INFO     | ddump.api.dump:download:151 - 下载 stock_zt_pool_em () {'date': '20231101'}
2024-07-29 22:13:27.843 | INFO     | ddump.api.dump:download:151 - 下载 stock_zt_pool_em () {'date': '20231101'}
2024-07-29 22:13:43.057 | INFO     | ddump.api.dump:download:151 - 下载 stock_zt_pool_em () {'date': '20231101'}
2024-07-29 22:13:58.275 | INFO     | ddump.api.dump:download:151 - 下载 stock_zt_pool_em () {'date': '20231101'}
2024-07-29 22:14:13.501 | INFO     | ddump.api.dump:download:151 - 下载 stock_zt_pool_em () {'date': '20231101'}
Traceback (most recent call last):
  File "E:\anaconda3\envs\freqtrade\Lib\site-packages\tenacity\__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "d:\1\ddump\examples\akshare\stock_zt_pool_em.py", line 49, in main
    d.download(kw=['date'])
  File "E:\anaconda3\envs\freqtrade\Lib\site-packages\ddump\api\dump.py", line 156, in download
    df = api(*self.args, **_kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\envs\freqtrade\Lib\site-packages\akshare\stock_feature\stock_ztb_em.py", line 50, in stock_zt_pool_em
    temp_df.columns = [
    ^^^^^^^^^^^^^^^
  File "E:\anaconda3\envs\freqtrade\Lib\site-packages\pandas\core\generic.py", line 6313, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "E:\anaconda3\envs\freqtrade\Lib\site-packages\pandas\core\generic.py", line 814, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "E:\anaconda3\envs\freqtrade\Lib\site-packages\pandas\core\internals\managers.py", line 238, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "E:\anaconda3\envs\freqtrade\Lib\site-packages\pandas\core\internals\base.py", line 98, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 1 elements, new values have 17 elements

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\1\ddump\examples\akshare\stock_zt_pool_em.py", line 57, in <module>
    main()
  File "E:\anaconda3\envs\freqtrade\Lib\site-packages\tenacity\__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\envs\freqtrade\Lib\site-packages\tenacity\__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\envs\freqtrade\Lib\site-packages\tenacity\__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "E:\anaconda3\envs\freqtrade\Lib\site-packages\tenacity\__init__.py", line 419, in exc_check
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1ba277136d0 state=finished raised ValueError>]

**Comment by wukan1986** [comment]
这是网站内容发生了变化，需要akshare进行相应的适配


https://github.com/akfamily/akshare/issues/4236
https://github.com/akfamily/akshare/issues/4914
